blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://registry.terraform.io/modules/jfreed-dev/modules/turingpi
    about: Check the Terraform Registry for module documentation
